const $=s=>document.querySelector(s),landing=$('#landing'),game=$('#game'),canvas=$('#world'),ctx=canvas.getContext('2d'),preview=$('#preview'),pctx=preview.getContext('2d');
let ws,id,room,tasks=[],done=new Set(),players=new Map(),ais=[],me={x:900,y:650,hp:100,alive:true},keys={},last=performance.now(),chatOpen=false,voiceOn=false,localStream=null,peers=new Map(),training=false;
const obstacles=[{x:0,y:0,w:1800,h:38},{x:0,y:1162,w:1800,h:38},{x:0,y:0,w:38,h:1200},{x:1762,y:0,w:38,h:1200},{x:510,y:120,w:38,h:410},{x:510,y:690,w:38,h:390},{x:1220,y:120,w:38,h:320},{x:1220,y:610,w:38,h:470},{x:700,y:520,w:400,h:38},{x:700,y:790,w:400,h:38},{x:840,y:558,w:38,h:95},{x:960,y:695,w:38,h:95}];
function look(){return{color:$('#color').value,hair:$('#hair').value}}function drawAvatar(c,x,y,l,name,dead=false,stunned=false,scale=1){c.save();c.translate(x,y);c.scale(scale,scale);c.globalAlpha=dead?.35:1;c.fillStyle='rgba(0,0,0,.32)';c.beginPath();c.ellipse(0,17,17,7,0,0,Math.PI*2);c.fill();c.fillStyle=l?.color||'#78e3cf';round(c,-14,-18,28,37,8);c.fill();c.fillStyle='#c5edf0';round(c,-9,-10,19,11,5);c.fill();c.fillStyle='#14232a';c.fillRect(-5,-7,11,3);c.fillStyle=l?.color||'#78e3cf';c.fillRect(-12,14,8,10);c.fillRect(5,14,8,10);c.fillStyle='#17212b';if(l?.hair==='cap'){c.beginPath();c.arc(0,-17,14,Math.PI,Math.PI*2);c.fill();c.fillRect(-15,-17,30,4)}else if(l?.hair==='spike'){c.beginPath();c.moveTo(-13,-16);c.lineTo(-8,-30);c.lineTo(-2,-19);c.lineTo(5,-32);c.lineTo(11,-17);c.fill()}else if(l?.hair==='antenna'){c.fillRect(-2,-31,4,14);c.beginPath();c.arc(0,-33,4,0,Math.PI*2);c.fill()}else{c.beginPath();c.arc(0,-19,13,Math.PI,0);c.fill()}if(stunned){c.strokeStyle='#eac26b';c.lineWidth=2;c.beginPath();c.arc(0,-30,17,0,Math.PI*1.6);c.stroke()}c.restore();if(name){c.save();c.font='700 12px system-ui';c.textAlign='center';c.fillStyle='rgba(6,9,13,.82)';const w=c.measureText(name).width+12;round(c,x-w/2,y-48,w,20,4);c.fill();c.fillStyle='#fff';c.fillText(name,x,y-34);c.restore()}}
function round(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r)}function renderPreview(){pctx.clearRect(0,0,96,96);drawAvatar(pctx,48,55,look(),null,false,false,1.4)}$('#color').onchange=$('#hair').onchange=renderPreview;renderPreview();
function connect(type,code){$('#error').textContent='接続中…';ws=new WebSocket((location.protocol==='https:'?'wss':'ws')+'://'+location.host+'/ws');ws.onopen=()=>ws.send(JSON.stringify({type,code,name:$('#name').value||'CREW',look:look()}));ws.onerror=()=>$('#error').textContent='サーバーに接続できません';ws.onmessage=e=>message(JSON.parse(e.data));ws.onclose=()=>{if(!training&&room)toast('接続が切れました')}}
$('#create').onclick=()=>connect('create');$('#join').onclick=()=>connect('join',$('#code').value);$('#quick').onclick=()=>{training=true;id='local';room='TRAIN';tasks=[{id:'reactor',x:280,y:280,name:'炉心を同期'},{id:'comms',x:1480,y:330,name:'通信を復旧'},{id:'coolant',x:1480,y:930,name:'冷却材を充填'},{id:'archive',x:320,y:950,name:'記録を復元'}];players.set(id,{id,name:$('#name').value,look:look(),x:900,y:650,hp:100,alive:true});enter()};
function message(m){if(m.type==='error')$('#error').textContent=m.message;if(m.type==='welcome'){id=m.id;room=m.room;tasks=m.tasks;done=new Set(m.done);players=new Map(m.players.map(p=>[p.id,p]));me=players.get(id);enter();for(const p of m.players)if(p.id!==id&&voiceOn)makeOffer(p.id)}if(m.type==='joined'){players.set(m.player.id,m.player);addMsg('SYSTEM',m.player.name+' が接続しました');if(voiceOn)makeOffer(m.player.id)}if(m.type==='left'){players.delete(m.id);closePeer(m.id)}if(m.type==='state'){players=new Map(m.players.map(p=>[p.id,p]));ais=m.ais;done=new Set(m.done);const serverMe=players.get(id);if(serverMe){me.hp=serverMe.hp;me.alive=serverMe.alive;players.set(id,{...serverMe,x:me.x,y:me.y})}updateHud()}if(m.type==='chat')addMsg(m.name,m.text,m.ai);if(m.type==='signal')signal(m);if(m.type==='end')end(m.result)}
function enter(){landing.classList.add('hidden');game.classList.remove('hidden');$('#roomCode').textContent=room;resize();updateHud();addMsg('SYSTEM','区画に接続。顔ではなく、行動を信じろ。')}
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio}addEventListener('resize',resize);
addEventListener('keydown',e=>{if(e.key==='Enter'){if(!chatOpen){chatOpen=true;$('#chatInput').classList.add('open');$('#chatInput').focus()}else sendChat();e.preventDefault();return}if(document.activeElement===$('#chatInput'))return;keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')doTask();if(e.code==='Space'){pulse();e.preventDefault()}if(e.key.toLowerCase()==='v')toggleVoice()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function sendChat(){const inp=$('#chatInput'),text=inp.value.trim();if(text){if(training)addMsg(me.name,text);else ws.send(JSON.stringify({type:'chat',text}))}inp.value='';inp.classList.remove('open');inp.blur();chatOpen=false}
function addMsg(name,text,ai=false){const el=document.createElement('div');el.className='msg'+(ai?' ai':'');el.textContent=name+': '+text;$('#messages').append(el);while($('#messages').children.length>7)$('#messages').firstChild.remove();setTimeout(()=>el.remove(),9000)}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1800)}
function doTask(){if(!me.alive)return;const t=tasks.find(t=>!done.has(t.id)&&Math.hypot(t.x-me.x,t.y-me.y)<80);if(!t)return toast('端末に近づいてください');done.add(t.id);toast(t.name+' — 完了');if(!training)ws.send(JSON.stringify({type:'task',id:t.id}));else if(done.size===tasks.length)end('won');updateHud()}
function pulse(){if(!me.alive)return;if(!training)ws.send(JSON.stringify({type:'pulse'}));toast('妨害パルスを放射')}
function updateHud(){const p=players.get(id)||me;$('#progress').style.width=(done.size/tasks.length*100||0)+'%';$('#objective').textContent=done.size===tasks.length?'脱出経路を確保':'端末を復旧せよ '+done.size+' / '+tasks.length;$('#online').textContent='● '+players.size+' ONLINE';$('#hpText').textContent=Math.max(0,Math.round(p.hp))+'%';$('#hpbar').style.width=Math.max(0,p.hp)+'%'}
function collide(nx,ny){return obstacles.some(o=>nx+14>o.x&&nx-14<o.x+o.w&&ny+20>o.y&&ny-20<o.y+o.h)}
function loop(now){const dt=Math.min(.035,(now-last)/1000);last=now;if(!game.classList.contains('hidden')){const p=players.get(id)||me;if(p.alive&&!chatOpen){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(dx||dy){const n=Math.hypot(dx,dy),sp=190;dx=dx/n*sp*dt;dy=dy/n*sp*dt;if(!collide(me.x+dx,me.y))me.x+=dx;if(!collide(me.x,me.y+dy))me.y+=dy;if(!training&&ws?.readyState===1)ws.send(JSON.stringify({type:'move',x:me.x,y:me.y}))}}if(training)trainingAI(dt);draw()}requestAnimationFrame(loop)}requestAnimationFrame(loop);
let trainingSpawn=0;function trainingAI(dt){trainingSpawn+=dt;if(trainingSpawn>8&&!ais.length){ais=[{id:'ai-local',name:me.name,look:me.look,x:90,y:90,hp:100,alive:true}];addMsg(me.name,'今そっちに向かってる',true)}for(const a of ais){const d=Math.hypot(me.x-a.x,me.y-a.y);a.x+=(me.x-a.x)/Math.max(d,1)*90*dt;a.y+=(me.y-a.y)/Math.max(d,1)*90*dt;if(d<32&&me.alive){me.hp-=24*dt;if(me.hp<=0){me.hp=0;me.alive=false;end('lost')}updateHud()}}players.set(id,{...players.get(id),x:me.x,y:me.y,hp:me.hp,alive:me.alive})}
function draw(){const W=canvas.width/devicePixelRatio,H=canvas.height/devicePixelRatio,camX=me.x-W/2,camY=me.y-H/2;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,W,H);ctx.save();ctx.translate(-camX,-camY);ctx.fillStyle='#0b1118';ctx.fillRect(0,0,1800,1200);ctx.strokeStyle='#15202b';ctx.lineWidth=1;for(let x=0;x<1800;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,1200);ctx.stroke()}for(let y=0;y<1200;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1800,y);ctx.stroke()}drawZones();for(const o of obstacles){ctx.fillStyle='#27323d';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#465360';ctx.strokeRect(o.x+.5,o.y+.5,o.w-1,o.h-1)}for(const t of tasks)drawTask(t);for(const a of ais)drawAvatar(ctx,a.x,a.y,a.look,a.name,!a.alive,a.stunned);for(const p of players.values())drawAvatar(ctx,p.id===id?me.x:p.x,p.id===id?me.y:p.y,p.look,p.name,!p.alive);ctx.restore();const g=ctx.createRadialGradient(W/2,H/2,90,W/2,H/2,Math.max(W,H)*.65);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.72,'rgba(0,0,0,.15)');g.addColorStop(1,'rgba(0,0,0,.67)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function drawZones(){const z=[['REACTOR',70,70,420,440],['COMMS',1280,70,450,450],['COOLANT',1280,690,450,440],['ARCHIVE',70,690,420,440],['CORE',570,570,610,180]];ctx.font='800 12px system-ui';for(const [n,x,y,w,h] of z){ctx.fillStyle='rgba(19,31,42,.72)';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#233442';ctx.strokeRect(x,y,w,h);ctx.fillStyle='#53687a';ctx.fillText(n,x+16,y+24)}}
function drawTask(t){const ok=done.has(t.id);ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle=ok?'#17372f':'#122a2d';ctx.strokeStyle=ok?'#4ea88d':'#6ee2ce';ctx.lineWidth=2;round(ctx,-24,-20,48,40,5);ctx.fill();ctx.stroke();ctx.fillStyle=ok?'#69bba5':'#8ff2de';ctx.font='900 18px monospace';ctx.textAlign='center';ctx.fillText(ok?'✓':'!',0,7);ctx.restore()}
function end(result){$('#endModal').classList.remove('hidden');$('#endTitle').textContent=result==='won'?'帰還経路、確保':'全生体信号、消失';$('#endIcon').textContent=result==='won'?'◇':'×';$('#endText').textContent=result==='won'?'端末は復旧した。だが、帰還した全員が本物とは限らない。':'MIMICは乗員の声と姿を学習し、区画を掌握した。'}
async function toggleVoice(){if(!voiceOn){try{localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});voiceOn=true;$('#voice').classList.add('live');$('#voice').textContent='V　VOICE ON';for(const p of players.values())if(p.id!==id)makeOffer(p.id);toast('ボイス接続を開始')}catch(e){toast('マイクを利用できません — チャットを使用')}}else{voiceOn=false;localStream?.getTracks().forEach(t=>t.stop());localStream=null;for(const k of peers.keys())closePeer(k);$('#voice').classList.remove('live');$('#voice').textContent='V　VOICE OFF'}}
function pcFor(pid){if(peers.has(pid))return peers.get(pid);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});if(localStream)localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));pc.onicecandidate=e=>{if(e.candidate)ws.send(JSON.stringify({type:'signal',to:pid,data:{candidate:e.candidate}}))};pc.ontrack=e=>{let a=document.getElementById('audio-'+pid);if(!a){a=document.createElement('audio');a.id='audio-'+pid;a.autoplay=true;document.body.append(a)}a.srcObject=e.streams[0]};peers.set(pid,pc);return pc}
async function makeOffer(pid){if(training||!voiceOn)return;const pc=pcFor(pid),offer=await pc.createOffer();await pc.setLocalDescription(offer);ws.send(JSON.stringify({type:'signal',to:pid,data:{sdp:pc.localDescription}}))}
async function signal(m){if(!voiceOn)return;const pc=pcFor(m.from);try{if(m.data.sdp){await pc.setRemoteDescription(m.data.sdp);if(m.data.sdp.type==='offer'){const ans=await pc.createAnswer();await pc.setLocalDescription(ans);ws.send(JSON.stringify({type:'signal',to:m.from,data:{sdp:pc.localDescription}}))}}else if(m.data.candidate)await pc.addIceCandidate(m.data.candidate)}catch(e){console.warn('voice',e)}}function closePeer(pid){peers.get(pid)?.close();peers.delete(pid);document.getElementById('audio-'+pid)?.remove()}
