const $=s=>document.querySelector(s),canvas=$('#world'),ctx=canvas.getContext('2d'),preview=$('#preview'),pctx=preview.getContext('2d');
const tasks=[{id:'reactor',x:280,y:280,name:'炉心を同期'},{id:'comms',x:1480,y:330,name:'通信を復旧'},{id:'coolant',x:1480,y:930,name:'冷却材を充填'},{id:'archive',x:320,y:950,name:'記録を復元'}];
const walls=[{x:0,y:0,w:1800,h:38},{x:0,y:1162,w:1800,h:38},{x:0,y:0,w:38,h:1200},{x:1762,y:0,w:38,h:1200},{x:510,y:120,w:38,h:410},{x:510,y:690,w:38,h:390},{x:1220,y:120,w:38,h:320},{x:1220,y:610,w:38,h:470},{x:700,y:520,w:400,h:38},{x:700,y:790,w:400,h:38},{x:840,y:558,w:38,h:95},{x:960,y:695,w:38,h:95}];
let mode='',id='',players=new Map(),me={x:900,y:650,hp:100,alive:true},done=new Set(),ais=[],keys={},last=performance.now(),chatOpen=false,localStream=null,hostPeers=new Map(),guestPc=null,guestDc=null,spawnAt=0,gameState='playing';
const rtc={iceServers:[{urls:'stun:stun.cloudflare.com:3478'},{urls:'stun:stun.l.google.com:19302'}]};
function look(){return{color:$('#color').value,hair:$('#hair').value}}function person(pid){return{id:pid,name:($('#name').value||'CREW').slice(0,16),look:look(),x:860+Math.random()*80,y:620+Math.random()*60,hp:100,alive:true}}
function rr(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r)}
function avatar(c,x,y,l,name,dead=false,stun=false,scale=1){c.save();c.translate(x,y);c.scale(scale,scale);c.globalAlpha=dead?.35:1;c.fillStyle='rgba(0,0,0,.35)';c.beginPath();c.ellipse(0,17,17,7,0,0,7);c.fill();c.fillStyle=l?.color||'#78e3cf';rr(c,-14,-18,28,37,8);c.fill();c.fillStyle='#c5edf0';rr(c,-9,-10,19,11,5);c.fill();c.fillStyle='#14232a';c.fillRect(-5,-7,11,3);c.fillStyle=l?.color||'#78e3cf';c.fillRect(-12,14,8,10);c.fillRect(5,14,8,10);c.fillStyle='#17212b';if(l?.hair==='cap'){c.beginPath();c.arc(0,-17,14,Math.PI,7);c.fill();c.fillRect(-15,-17,30,4)}else if(l?.hair==='spike'){c.beginPath();c.moveTo(-13,-16);c.lineTo(-8,-30);c.lineTo(-2,-19);c.lineTo(5,-32);c.lineTo(11,-17);c.fill()}else if(l?.hair==='antenna'){c.fillRect(-2,-31,4,14);c.beginPath();c.arc(0,-33,4,0,7);c.fill()}else{c.beginPath();c.arc(0,-19,13,Math.PI,0);c.fill()}if(stun){c.strokeStyle='#eac26b';c.lineWidth=2;c.beginPath();c.arc(0,-30,17,0,5);c.stroke()}c.restore();if(name){c.save();c.font='700 12px system-ui';c.textAlign='center';const w=c.measureText(name).width+12;c.fillStyle='rgba(6,9,13,.82)';rr(c,x-w/2,y-48,w,20,4);c.fill();c.fillStyle='#fff';c.fillText(name,x,y-34);c.restore()}}
function drawPreview(){pctx.clearRect(0,0,96,96);avatar(pctx,48,55,look(),null,false,false,1.4)}$('#color').onchange=$('#hair').onchange=drawPreview;drawPreview();
async function mic(){if(localStream)return;try{localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}})}catch(e){toast('マイクなしで接続します')}}
function audioFor(pc,pid){pc.ontrack=e=>{let a=document.getElementById('audio-'+pid);if(!a){a=document.createElement('audio');a.id='audio-'+pid;a.autoplay=true;document.body.append(a)}a.srcObject=e.streams[0]}}
async function encode(obj){const raw=new TextEncoder().encode(JSON.stringify(obj));try{const cs=new CompressionStream('gzip'),w=cs.writable.getWriter();w.write(raw);w.close();const b=new Uint8Array(await new Response(cs.readable).arrayBuffer());return 'G.'+b64(b)}catch{return 'J.'+b64(raw)}}
async function decode(s){const [kind,data]=s.trim().split('.',2),bytes=unb64(data||kind);let raw=bytes;if(kind==='G'){const ds=new DecompressionStream('gzip'),w=ds.writable.getWriter();w.write(bytes);w.close();raw=new Uint8Array(await new Response(ds.readable).arrayBuffer())}return JSON.parse(new TextDecoder().decode(raw))}
function b64(bytes){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function unb64(s){s=s.replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function localDesc(pc,desc){await pc.setLocalDescription(desc);if(pc.iceGatheringState!=='complete')await new Promise(r=>{const t=setTimeout(r,5000);pc.addEventListener('icegatheringstatechange',()=>{if(pc.iceGatheringState==='complete'){clearTimeout(t);r()}},{once:false})});return pc.localDescription}
function modal(title,html){$('#pairTitle').textContent=title;$('#pairBody').innerHTML=html;$('#pairState').textContent='';$('#pairModal').classList.remove('hidden')}
$('#pairClose').onclick=()=>$('#pairModal').classList.add('hidden');
async function copyFrom(sel){const el=$(sel);try{await navigator.clipboard.writeText(el.value);toast('コードをコピーしました')}catch{el.select();document.execCommand('copy');toast('コードをコピーしました')}}
async function hostInvite(){if(!mode){mode='host';id='host-'+crypto.randomUUID().slice(0,6);me=person(id);players.set(id,me);spawnAt=Date.now()+12000;enter();$('#pairMore').classList.remove('hidden')}modal('招待コードを作成中','<p class="steps">マイクの許可後、接続情報を作成します。</p>');await mic();const pid='guest-'+crypto.randomUUID().slice(0,6),pc=new RTCPeerConnection(rtc);if(localStream)localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));audioFor(pc,pid);const dc=pc.createDataChannel('null-shift');hostChannel(pid,pc,dc);const offer=await localDesc(pc,await pc.createOffer());hostPeers.set(pid,{pc,dc});const code=await encode(offer);modal('ホスト：招待を送る',`<p class="steps">① 下の招待コードを相手へ送る<br>② 相手から返された応答コードを貼る</p><label class="label">招待コード</label><textarea id="offerOut" readonly>${code}</textarea><div class="pair-actions"><button id="copyOffer" class="copy">招待をコピー</button></div><label class="label">相手の応答コード</label><textarea id="answerIn" placeholder="ここに応答コードを貼り付け"></textarea><button id="applyAnswer" class="primary" style="width:100%;margin-top:10px">応答を適用</button><p class="pair-note">コードは接続後に無効になります。</p>`);$('#copyOffer').onclick=()=>copyFrom('#offerOut');$('#applyAnswer').onclick=async()=>{try{await pc.setRemoteDescription(await decode($('#answerIn').value));$('#pairState').textContent='応答を適用しました。接続を待っています…'}catch(e){$('#pairState').textContent='コードを読み取れません'}}}
function hostChannel(pid,pc,dc){dc.onopen=()=>{const p=person(pid);players.set(pid,p);send(dc,{type:'welcome',id:pid,tasks,players:[...players.values()],done:[...done]});broadcast({type:'chat',name:'SYSTEM',text:p.name+' が接続しました'});$('#pairState').textContent='接続完了';updateHud()};dc.onmessage=e=>hostMessage(pid,JSON.parse(e.data));dc.onclose=()=>{players.delete(pid);hostPeers.delete(pid);updateHud()}}
async function joinFlow(){mode='guest';modal('ゲスト：招待を入力',`<p class="steps">ホストから受け取った招待コードを貼ってください。</p><label class="label">ホストの招待コード</label><textarea id="offerIn" placeholder="ここに招待コードを貼り付け"></textarea><button id="makeAnswer" class="primary" style="width:100%;margin-top:10px">応答コードを生成</button>`);$('#makeAnswer').onclick=async()=>{try{$('#pairState').textContent='接続情報を作成中…';await mic();guestPc=new RTCPeerConnection(rtc);if(localStream)localStream.getTracks().forEach(t=>guestPc.addTrack(t,localStream));audioFor(guestPc,'host');guestPc.ondatachannel=e=>guestChannel(e.channel);await guestPc.setRemoteDescription(await decode($('#offerIn').value));const ans=await localDesc(guestPc,await guestPc.createAnswer()),code=await encode(ans);modal('ゲスト：応答を返す',`<p class="steps">この応答コードをホストへ送り、ホスト側で「応答を適用」してもらってください。</p><label class="label">応答コード</label><textarea id="answerOut" readonly>${code}</textarea><button id="copyAnswer" class="copy" style="width:100%;margin-top:10px">応答をコピー</button><p class="pair-note">適用されると自動的にゲームへ接続します。</p>`);$('#copyAnswer').onclick=()=>copyFrom('#answerOut')}catch(e){console.error(e);$('#pairState').textContent='招待コードを読み取れません'}}}
function guestChannel(dc){guestDc=dc;dc.onopen=()=>$('#pairState').textContent='ホストへ接続しました';dc.onmessage=e=>clientMessage(JSON.parse(e.data));dc.onclose=()=>toast('ホストとの接続が切れました')}
function send(dc,obj){if(dc?.readyState==='open')dc.send(JSON.stringify(obj))}function broadcast(obj){for(const x of hostPeers.values())send(x.dc,obj);clientMessage(obj)}
function hostMessage(pid,m){const p=players.get(pid);if(!p)return;if(m.type==='move'&&p.alive){p.x=Math.max(52,Math.min(1748,+m.x||p.x));p.y=Math.max(52,Math.min(1148,+m.y||p.y))}if(m.type==='task')finishTask(p,m.id);if(m.type==='pulse')pulseAt(p);if(m.type==='chat'){const text=String(m.text||'').slice(0,120);if(text)broadcast({type:'chat',name:p.name,text})}}
function clientMessage(m){if(m.type==='welcome'){id=m.id;players=new Map(m.players.map(p=>[p.id,p]));me=players.get(id);done=new Set(m.done);enter();$('#pairModal').classList.add('hidden')}if(m.type==='state'){players=new Map(m.players.map(p=>[p.id,p]));ais=m.ais;done=new Set(m.done);const p=players.get(id);if(p){me.hp=p.hp;me.alive=p.alive;players.set(id,{...p,x:me.x,y:me.y})}updateHud()}if(m.type==='chat')addMsg(m.name,m.text,!!m.ai);if(m.type==='end')end(m.result)}
$('#host').onclick=hostInvite;$('#join').onclick=joinFlow;$('#pairMore').onclick=hostInvite;$('#quick').onclick=()=>{mode='solo';id='solo';me=person(id);players.set(id,me);spawnAt=Date.now()+8000;enter()};
function enter(){$('#landing').classList.add('hidden');$('#game').classList.remove('hidden');$('#roomCode').textContent=mode==='host'?'HOST':mode==='guest'?'GUEST':'TRAIN';resize();updateHud();addMsg('SYSTEM','顔ではなく、行動を信じろ。')}
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio}addEventListener('resize',resize);
addEventListener('keydown',e=>{if(e.key==='Enter'){if(!chatOpen){chatOpen=true;$('#chatInput').classList.add('open');$('#chatInput').focus()}else sendChat();e.preventDefault();return}if(document.activeElement===$('#chatInput'))return;keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')tryTask();if(e.code==='Space'){doPulse();e.preventDefault()}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function sendChat(){const input=$('#chatInput'),text=input.value.trim();if(text){if(mode==='host'||mode==='solo')broadcast({type:'chat',name:me.name,text});else send(guestDc,{type:'chat',text})}input.value='';input.classList.remove('open');input.blur();chatOpen=false}
function addMsg(name,text,ai=false){const e=document.createElement('div');e.className='msg'+(ai?' ai':'');e.textContent=name+': '+text;$('#messages').append(e);while($('#messages').children.length>7)$('#messages').firstChild.remove();setTimeout(()=>e.remove(),9000)}function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1900)}
function finishTask(p,tid){const t=tasks.find(x=>x.id===tid);if(t&&!done.has(tid)&&Math.hypot(t.x-p.x,t.y-p.y)<80){done.add(tid);broadcast({type:'chat',name:'SYSTEM',text:t.name+' — 完了'})}}
function tryTask(){if(!me.alive)return;const t=tasks.find(t=>!done.has(t.id)&&Math.hypot(t.x-me.x,t.y-me.y)<80);if(!t)return toast('端末に近づいてください');if(mode==='guest')send(guestDc,{type:'task',id:t.id});else finishTask(me,t.id)}function pulseAt(p){for(const a of ais)if(Math.hypot(a.x-p.x,a.y-p.y)<115)a.stun=Date.now()+1800}function doPulse(){if(!me.alive)return;if(mode==='guest')send(guestDc,{type:'pulse'});else pulseAt(me);toast('妨害パルスを放射')}
function collision(x,y){return walls.some(o=>x+14>o.x&&x-14<o.x+o.w&&y+20>o.y&&y-20<o.y+o.h)}
function updateSim(dt){if((mode!=='host'&&mode!=='solo')||gameState!=='playing')return;if(Date.now()>spawnAt&&ais.length<Math.max(1,Math.floor(players.size/2))){const live=[...players.values()].filter(p=>p.alive),src=live[Math.floor(Math.random()*live.length)];if(src){const spots=[[90,90],[1710,90],[90,1110],[1710,1110]],s=spots[Math.floor(Math.random()*4)];ais.push({id:'m-'+crypto.randomUUID().slice(0,5),name:src.name,look:src.look,x:s[0],y:s[1],alive:true,hp:100,stun:0,lastHit:0});broadcast({type:'chat',name:src.name,text:'合流する。今どこ？',ai:true})}spawnAt=Date.now()+26000}for(const a of ais){if(Date.now()<a.stun)continue;let target,best=1e9;for(const p of players.values())if(p.alive){const d=Math.hypot(a.x-p.x,a.y-p.y);if(d<best){best=d;target=p}}if(target){const d=Math.max(1,best);a.x+=(target.x-a.x)/d*100*dt;a.y+=(target.y-a.y)/d*100*dt;if(best<34&&Date.now()-a.lastHit>850){target.hp=Math.max(0,target.hp-18);a.lastHit=Date.now();if(!target.hp){target.alive=false;broadcast({type:'chat',name:'SYSTEM',text:target.name+' の生体信号が消失'})}}}}if(done.size===tasks.length){gameState='won';broadcast({type:'end',result:'won'})}else if(players.size&&[...players.values()].every(p=>!p.alive)){gameState='lost';broadcast({type:'end',result:'lost'})}if(mode==='host')broadcastState()}
let stateClock=0;function broadcastState(){const now=performance.now();if(now-stateClock<50)return;stateClock=now;const m={type:'state',players:[...players.values()],ais,done:[...done]};for(const x of hostPeers.values())send(x.dc,m)}
function frame(now){const dt=Math.min(.035,(now-last)/1000);last=now;if(!$('#game').classList.contains('hidden')){const p=players.get(id)||me;if(p.alive&&!chatOpen){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(dx||dy){const n=Math.hypot(dx,dy),s=190;dx=dx/n*s*dt;dy=dy/n*s*dt;if(!collision(me.x+dx,me.y))me.x+=dx;if(!collision(me.x,me.y+dy))me.y+=dy;if(mode==='guest')send(guestDc,{type:'move',x:me.x,y:me.y});else{p.x=me.x;p.y=me.y}}}updateSim(dt);updateHud();draw()}requestAnimationFrame(frame)}requestAnimationFrame(frame);
function updateHud(){const p=players.get(id)||me,$n=players.size||1;$('#progress').style.width=(done.size/tasks.length*100)+'%';$('#objective').textContent='端末を復旧せよ '+done.size+' / '+tasks.length;$('#online').textContent='● '+$n+' ONLINE';$('#hpText').textContent=Math.round(p.hp||0)+'%';$('#hpbar').style.width=Math.max(0,p.hp||0)+'%'}
function zones(){const z=[['REACTOR',70,70,420,440],['COMMS',1280,70,450,450],['COOLANT',1280,690,450,440],['ARCHIVE',70,690,420,440],['CORE',570,570,610,180]];ctx.font='800 12px system-ui';for(const [n,x,y,w,h] of z){ctx.fillStyle='rgba(19,31,42,.72)';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#233442';ctx.strokeRect(x,y,w,h);ctx.fillStyle='#53687a';ctx.fillText(n,x+16,y+24)}}function drawTask(t){const ok=done.has(t.id);ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle=ok?'#17372f':'#122a2d';ctx.strokeStyle=ok?'#4ea88d':'#6ee2ce';ctx.lineWidth=2;rr(ctx,-24,-20,48,40,5);ctx.fill();ctx.stroke();ctx.fillStyle=ok?'#69bba5':'#8ff2de';ctx.font='900 18px monospace';ctx.textAlign='center';ctx.fillText(ok?'✓':'!',0,7);ctx.restore()}
function draw(){const W=canvas.width/devicePixelRatio,H=canvas.height/devicePixelRatio,cx=me.x-W/2,cy=me.y-H/2;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,W,H);ctx.save();ctx.translate(-cx,-cy);ctx.fillStyle='#0b1118';ctx.fillRect(0,0,1800,1200);ctx.strokeStyle='#15202b';for(let x=0;x<1800;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,1200);ctx.stroke()}for(let y=0;y<1200;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1800,y);ctx.stroke()}zones();for(const o of walls){ctx.fillStyle='#27323d';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#465360';ctx.strokeRect(o.x+.5,o.y+.5,o.w-1,o.h-1)}for(const t of tasks)drawTask(t);for(const a of ais)avatar(ctx,a.x,a.y,a.look,a.name,!a.alive,Date.now()<a.stun);for(const p of players.values())avatar(ctx,p.id===id?me.x:p.x,p.id===id?me.y:p.y,p.look,p.name,!p.alive);ctx.restore();const g=ctx.createRadialGradient(W/2,H/2,90,W/2,H/2,Math.max(W,H)*.65);g.addColorStop(0,'transparent');g.addColorStop(1,'rgba(0,0,0,.66)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function end(r){$('#endModal').classList.remove('hidden');$('#endTitle').textContent=r==='won'?'帰還経路、確保':'全生体信号、消失';$('#endIcon').textContent=r==='won'?'◇':'×';$('#endText').textContent=r==='won'?'端末は復旧した。帰還した全員が本物とは限らない。':'MIMICは乗員の声と姿を学習し、区画を掌握した。'}
