const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000,ROOT=path.join(__dirname,'public'),rooms=new Map();
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'};
const server=http.createServer((req,res)=>{let p=req.url.split('?')[0];if(p==='/')p='/index.html';p=path.normalize(p).replace(/^(\.\.[/\\])+/, '');const f=path.join(ROOT,p);if(!f.startsWith(ROOT))return res.writeHead(403).end();fs.readFile(f,(e,d)=>{if(e)return res.writeHead(404).end('Not found');res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store'});res.end(d)})});
function frame(data){const b=Buffer.from(data),len=b.length;if(len<126)return Buffer.concat([Buffer.from([129,len]),b]);if(len<65536){const h=Buffer.alloc(4);h[0]=129;h[1]=126;h.writeUInt16BE(len,2);return Buffer.concat([h,b])}const h=Buffer.alloc(10);h[0]=129;h[1]=127;h.writeBigUInt64BE(BigInt(len),2);return Buffer.concat([h,b])}
function send(c,o){if(c&&c.socket&&!c.socket.destroyed)c.socket.write(frame(JSON.stringify(o)))}
function broadcast(r,o,except){for(const p of r.players.values())if(p!==except)send(p,o)}
function parseFrames(c,chunk){c.buf=Buffer.concat([c.buf||Buffer.alloc(0),chunk]);while(c.buf.length>=2){const b=c.buf,opcode=b[0]&15,masked=b[1]&128,len7=b[1]&127;let off=2,len=len7;if(len7===126){if(b.length<4)return;len=b.readUInt16BE(2);off=4}else if(len7===127){if(b.length<10)return;len=Number(b.readBigUInt64BE(2));off=10}if(masked)off+=4;if(b.length<off+len)return;let payload=b.subarray(off,off+len);if(masked){const mask=b.subarray(off-4,off);payload=Buffer.from(payload.map((v,i)=>v^mask[i%4]))}c.buf=b.subarray(off+len);if(opcode===8){c.socket.end();return}if(opcode===9){const pong=Buffer.concat([Buffer.from([138,payload.length]),payload]);c.socket.write(pong);continue}if(opcode===1)try{handle(c,JSON.parse(payload.toString()))}catch(e){send(c,{type:'error',message:'Invalid message'})}}}
server.on('upgrade',(req,socket)=>{if(req.url!='/ws')return socket.destroy();const key=req.headers['sec-websocket-key'];if(!key)return socket.destroy();const accept=crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');const c={socket,id:crypto.randomUUID().slice(0,8),buf:Buffer.alloc(0)};socket.on('data',d=>parseFrames(c,d));socket.on('close',()=>leave(c));socket.on('error',()=>leave(c))});
function code(){let s;do{s=Math.random().toString(36).slice(2,8).toUpperCase()}while(rooms.has(s));return s}
function makeRoom(){const r={code:code(),players:new Map(),tasks:[{id:'reactor',x:280,y:280,name:'炉心を同期'},{id:'comms',x:1480,y:330,name:'通信を復旧'},{id:'coolant',x:1480,y:930,name:'冷却材を充填'},{id:'archive',x:320,y:950,name:'記録を復元'}],done:new Set(),ais:[],state:'playing',started:Date.now(),aiSpawn:Date.now()+12000};rooms.set(r.code,r);return r}
function player(c,m){return {socket:c.socket,conn:c,id:c.id,name:String(m.name||'CREW').slice(0,16),look:m.look||{},x:860+Math.random()*100,y:610+Math.random()*80,hp:100,alive:true,lastPulse:0}}
function handle(c,m){if(m.type==='create'||m.type==='join'){if(c.room)return;let r=m.type==='create'?makeRoom():rooms.get(String(m.code||'').toUpperCase());if(!r)return send(c,{type:'error',message:'ルームが見つかりません'});if(r.players.size>=8)return send(c,{type:'error',message:'ルームは満員です'});const p=player(c,m);c.room=r;c.player=p;r.players.set(p.id,p);send(p,{type:'welcome',id:p.id,room:r.code,tasks:r.tasks,players:[...r.players.values()].map(clean),done:[...r.done]});broadcast(r,{type:'joined',player:clean(p)},p);broadcastState(r);return}if(!c.room||!c.player)return;if(m.type==='move'&&c.player.alive){c.player.x=clamp(+m.x||0,52,1748);c.player.y=clamp(+m.y||0,52,1148)}else if(m.type==='task'&&c.player.alive){const t=c.room.tasks.find(t=>t.id===m.id);if(t&&dist(c.player,t)<75)c.room.done.add(t.id)}else if(m.type==='pulse'&&c.player.alive&&Date.now()-c.player.lastPulse>4500){c.player.lastPulse=Date.now();for(const a of c.room.ais)if(dist(c.player,a)<115)a.stun=Date.now()+1800}else if(m.type==='chat'){const text=String(m.text||'').trim().slice(0,120);if(text)broadcast(c.room,{type:'chat',name:c.player.name,text,id:c.player.id})}else if(m.type==='signal'){const to=c.room.players.get(m.to);if(to)send(to,{type:'signal',from:c.player.id,data:m.data})}}
function clean(p){return {id:p.id,name:p.name,look:p.look,x:p.x,y:p.y,hp:p.hp,alive:p.alive}}
function leave(c){const r=c.room,p=c.player;if(!r||!p||!r.players.has(p.id))return;r.players.delete(p.id);broadcast(r,{type:'left',id:p.id});if(!r.players.size)rooms.delete(r.code)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function spawnAI(r){const live=[...r.players.values()].filter(p=>p.alive);if(!live.length)return;const src=live[Math.floor(Math.random()*live.length)],spots=[[90,90],[1710,90],[90,1110],[1710,1110]],s=spots[Math.floor(Math.random()*spots.length)];r.ais.push({id:'ai-'+crypto.randomUUID().slice(0,6),name:src.name,look:src.look,x:s[0],y:s[1],hp:100,alive:true,copyId:src.id,stun:0,lastHit:0});broadcast(r,{type:'chat',name:src.name,text:['合流する、今どこ？','タスク終わった','こっちは安全そう'][Math.floor(Math.random()*3)],ai:true});}
function tickRoom(r,dt){const live=[...r.players.values()].filter(p=>p.alive);if(r.state!=='playing')return;if(Date.now()>r.aiSpawn&&r.ais.length<Math.max(1,Math.floor(r.players.size/2))){spawnAI(r);r.aiSpawn=Date.now()+26000}for(const a of r.ais){if(Date.now()<a.stun)continue;let target=null,best=1e9;for(const p of live){const d=dist(a,p);if(d<best){best=d;target=p}}if(target){const dx=target.x-a.x,dy=target.y-a.y,d=Math.max(1,Math.hypot(dx,dy));const speed=best<260?86:112;a.x+=dx/d*speed*dt;a.y+=dy/d*speed*dt;if(best<34&&Date.now()-a.lastHit>850){target.hp=Math.max(0,target.hp-18);a.lastHit=Date.now();if(target.hp<=0){target.alive=false;broadcast(r,{type:'chat',name:'SYSTEM',text:target.name+' の生体信号が消失'})}}}}if(r.done.size===r.tasks.length){r.state='won';broadcast(r,{type:'end',result:'won'})}else if(live.length&&live.every(p=>!p.alive)){r.state='lost';broadcast(r,{type:'end',result:'lost'})}}
function broadcastState(r){broadcast(r,{type:'state',players:[...r.players.values()].map(clean),ais:r.ais.map(a=>({...clean(a),stunned:Date.now()<a.stun})),done:[...r.done],state:r.state})}
let last=Date.now();setInterval(()=>{const now=Date.now(),dt=Math.min(.05,(now-last)/1000);last=now;for(const r of rooms.values()){tickRoom(r,dt);broadcastState(r)}},50);
server.listen(PORT,'0.0.0.0',()=>console.log(`NULL//SHIFT online at http://localhost:${PORT}`));
